// 组件列表的配置项
import * as dft from './default'
import * as styleFormConfig from './styleFormConfig'
export const WIDGET_LIST = [{
    type: 'basicBar',
    component: 'basicBar',
    label: '基础柱状图',
    default: dft.Basic_Bar,
    styles: dft.Basic_Bar_Style,
    styleForm: styleFormConfig.Basic_Bar,
  },
  {
    type: 'basicLine',
    component: 'basicLine',
    label: '基础折线图',
    default: dft.Basic_Line,
    styles: dft.Basic_Line_Style,
    styleForm: styleFormConfig.Basic_Line,
  },
  {
    type: 'areaLine',
    component: 'areaLine',
    label: '基础面积图',
    default: dft.Area_Bar,
    styles: dft.Area_Bar_Style,
    styleForm: styleFormConfig.Area_Bar,
  },
  {
    type: 'smoothLine',
    component: 'smoothLine',
    label: '平滑折线图',
    default: dft.Smooth_Line,
    styles: dft.Smooth_Line_Style,
    styleForm: styleFormConfig.Smooth_Line,
  },
  {
    type: 'pieBorder',
    component: 'pieBorder',
    label: '环形图',
    default: dft.Pie_Border,
    styles: dft.Pie_Border_Style,
    styleForm: styleFormConfig.Pie_Border,
  },
  {
    type: 'basicPie',
    component: 'basicPie',
    label: '饼状图',
    default: dft.Basic_Pie,
    styles: dft.Basic_Pie_Style,
    styleForm: styleFormConfig.Basic_Pie,
  },
  {
    type: 'pieHalf',
    component: 'pieHalf',
    label: '半环形图',
    default: dft.pie_Half_Pie,
    styles: dft.pie_Half_Pie_Style,
    styleForm: styleFormConfig.pie_Half_Pie,
  },
  {
    type: 'basicScatter',
    component: 'basicScatter',
    lable: '基础散点图',
    default: dft.Basic_Scatter,
    styles: dft.Basic_Scatter_Style,
    styleForm: styleFormConfig.Basic_Scatter,
  },
  {
    type: 'exponentialRegression',
    component: 'exponentialRegression',
    lable: '线性回归图',
    default: dft.Exponential_Regression,
    styles: dft.Exponential_Regression_Style,
    styleForm: styleFormConfig.Exponential_Regression,
  },
  {
    type: 'spFunnel',
    component: 'spFunnel',
    lable: '特殊漏斗图',
    default: dft.Sp_funnel,
    styles: dft.Sp_funnel_Style,
    styleForm: styleFormConfig.Sp_funnel,
  },
  {
    type: 'basicFunnel',
    component: 'basicFunnel',
    label: '基础漏斗图',
    default: dft.Basic_funnel,
    styles: dft.Basic_funnel_Style,
    styleForm: styleFormConfig.Basic_funnel,
  },
  {
    type: 'basicGauge',
    component: 'basicGauge',
    label: '基础仪表盘',
    default: dft.Basic_gauge,
    styles: dft.Basic_gauge_Style,
    styleForm: styleFormConfig.Basic_gauge,
  },
  {
    type: 'gradeGauge',
    component: 'gradeGauge',
    label: '等级仪表盘',
    default: dft.Grade_gauge,
    styles: dft.Grade_gauge_Style,
    styleForm: styleFormConfig.Grade_gauge,
  },
  {
    type: 'barWithNegative',
    component: 'barWithNegative',
    label: '交错正负轴柱状图',
    default: dft.Bar_With_Negative,
    styles: dft.Bar_With_Negative_Style,
    styleForm: styleFormConfig.Bar_With_Negative,
  },
  {
    type: 'HBar',
    component: 'HBar',
    label: '条形图',
    default: dft.HBar,
    styles: dft.HBar_Style,
    styleForm: styleFormConfig.HBar,
  },
  {
    type: 'barLine',
    component: 'barLine',
    label: '柱状折线图',
    default: dft.Bar_Line,
    styles: dft.Bar_Line_Style,
    styleForm: styleFormConfig.Bar_Line,
  }
];